---
- name: Install packages for BeeGFS client
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
  - beegfs-client
  - beegfs-helperd
  - beegfs-utils
  notify: Restart BeeGFS client service

- name: Detect the version of the running kernel
  command: "uname -r"
  register: kernel_version
  changed_when: false

- name: Define client kernel build for IB
  block:
  - name: Define client kernel build for IB
    lineinfile: 
      path: "/etc/beegfs/beegfs-client-autobuild.conf"
      regexp: "^buildArgs="
      line: "buildArgs=-j8 BEEGFS_OPENTK_IBVERBS=1"
    notify: Restart BeeGFS client service
  - name: Ensure kernel development headers are present
    package:
      name: "kernel-devel-{{ kernel_version.stdout }}"
      state: present
    notify: Restart BeeGFS client service
  become: yes
  when: beegfs_rdma | bool

- name: Ensure gcc is installed
  package:
    name: "gcc"
    state: present
  become: yes
  notify: Restart BeeGFS client service

- name: Rebuild the BeeGFS client kernel module
  command: /etc/init.d/beegfs-client rebuild
  args:
    creates: "/lib/modules/{{kernel_version.stdout}}/updates/fs/beegfs_autobuild/beegfs.ko"
  become: yes
  notify: Restart BeeGFS client service

- name: Ensure the BeeGFS mount point exists
  file:
    path: "{{ item.beegfs_path_client }}"
    state: directory
  become: yes
  notify: Restart BeeGFS client service
  with_items: "{{ beegfs_client_confs }}"

- name: Copy over beegfs-mounts config file
  template:
    src: beegfs-mounts.conf.j2
    dest: /etc/beegfs/beegfs-mounts.conf
    mode: 0644
  become: yes 
  notify: Restart BeeGFS client service

- name: Make of copy of BeeGFS client config file if it doesn't exist
  copy:
    remote_src: yes
    src: /etc/beegfs/beegfs-client.conf
    dest: "/etc/beegfs/beegfs-client-{{ item.beegfs_host_mgmt }}.conf"
    force: no
  become: yes
  with_items: "{{ beegfs_client_confs }}"
  notify: Restart BeeGFS client service

- name: Configure beegfs-client config file to point to the specified management host
  lineinfile:
    dest: "/etc/beegfs/beegfs-client-{{ item.beegfs_host_mgmt }}.conf"
    regexp: "^sysMgmtdHost"
    line: "sysMgmtdHost = {{ item.beegfs_host_mgmt }}"
  with_items: "{{ beegfs_client_confs }}"
  become: yes

- name: Configure beegfs-client config file to use the specified port
  lineinfile:
    dest: "/etc/beegfs/beegfs-client-{{ item.beegfs_host_mgmt }}.conf"
    regexp: "^connClientPortUDP"
    line: "connClientPortUDP = {{ item.beegfs_port_client | default(beegfs_port_client) }}"
  with_items: "{{ beegfs_client_confs }}"
  become: yes

- name: Configure beegfs-client config file to ensure the specifed connection interface is used
  lineinfile:
    dest: "/etc/beegfs/beegfs-client-{{ item.beegfs_host_mgmt }}.conf"
    regexp: "^connInterfacesFile"
    line: "connInterfacesFile = /etc/beegfs/connInterfacesFile"
  with_items: "{{ beegfs_client_confs }}"
  become: yes

- name: Copy default beegfs-client config file to enable beegfs_ctl in the management host
  copy:
    remote_src: yes
    dest: /etc/beegfs/beegfs-client.conf
    src: "/etc/beegfs/beegfs-client-{{ item.beegfs_host_mgmt }}.conf"
    force: yes
  with_items: "{{ beegfs_client_confs }}"
  when: item.beegfs_host_mgmt == inventory_hostname
  become: yes
...
