---
- name: Ensure the BeeGFS package repo is defined
  get_url:
    url: "{{ beegfs_repo_url }}"
    dest: /etc/yum.repos.d/beegfs-rhel7.repo
  become: yes

# Task flow inspired by MichaelRigart.interfaces role - thanks markgoddard
# Some systems do not support /etc/modules-load.d, in which case we fall back
# to /etc/modules.
- name: Check whether /etc/modules-load.d exists
  stat:
    path: /etc/modules-load.d
  register: modules_load_stat

- name: Ensure any required kernel modules are loaded
  modprobe:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ beegfs_kmod_preload }}"

- name: Make sure required modules are loaded at boot via /etc/modules-load.d
  lineinfile:
    dest: /etc/modules-load.d/beegfs.conf
    line: "{{ item }}"
    create: yes
  become: yes
  when: modules_load_stat.stat.exists
  with_items: "{{ beegfs_kmod_preload }}"

- name: Make sure required modules are loaded at boot via /etc/modules
  lineinfile:
    dest: /etc/modules
    line: "{{ item }}"
  become: yes
  when: not modules_load_stat.stat.exists
  with_items: "{{ beegfs_kmod_preload }}"

- include: mgmt.yml
  when: beegfs_enable.mgmt

- include: admon.yml
  when: beegfs_enable.admon

- include: meta.yml
  when: beegfs_enable.meta

- include: oss.yml
  when: beegfs_enable.oss

- include: client.yml
  when: beegfs_enable.client and beegfs_path_client not in ansible_mounts

- name: Create connInterfacesFile
  template:
    src: connInterfacesFile.j2
    dest: /etc/beegfs/connInterfacesFile
  become: yes

- name: Enable and start BeeGFS mgmt service
  service:
    name: beegfs-mgmtd
    enabled: yes
    state: restarted
  become: yes
  when: beegfs_enable.mgmt

- name: Enable and start BeeGFS meta service
  service:
    name: beegfs-meta
    enabled: yes
    state: restarted
  become: yes
  when: beegfs_enable.meta

- name: Enable and start BeeGFS storage service
  service:
    name: beegfs-storage
    enabled: yes
    state: restarted
  become: yes
  when: beegfs_enable.oss

- name: Enable and start BeeGFS client service
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  become: yes
  with_items:
  - beegfs-helperd
  - beegfs-client
  when: beegfs_enable.client
  retries: 3
  delay: 3
  register: result
  until: result is success

- name: Enable and start BeeGFS admon service
  service:
    name: beegfs-admon
    enabled: yes
    state: restarted
  become: yes
  when: beegfs_enable.admon
...
